Repository YOUNGHO0/Filmdoms_Project, pull requests merged in 2023-02, with the labels that each got.

#2 유즈케이스 다이어그램 업로드
  document/FilmdomsUseCase_Admin.png
  document/FilmdomsUsecase_User.png
Labels: documentation

#6 스프링부트 프로젝트 초기화
  .gitignore
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/filmdoms/community/CommunityApplication.java
  src/main/resources/application.properties
  src/test/java/com/filmdoms/community/CommunityApplicationTests.java
Labels: documentation, enhancement

#15 로그인시 JWT 인증 오류 버그 수정
  src/main/java/com/filmdoms/community/account/config/jwt/JwtTokenProvider.java
Labels: bug

#16 메인 페이지 영화 후기 호출 구현
  src/main/java/com/filmdoms/community/CommunityApplication.java
  src/main/java/com/filmdoms/community/account/config/SecurityConfig.java
  src/main/java/com/filmdoms/community/review/controller/MovieReviewController.java
  src/main/java/com/filmdoms/community/review/data/constant/CommentStatus.java
  src/main/java/com/filmdoms/community/review/data/constant/MovieReviewTag.java
  src/main/java/com/filmdoms/community/review/data/constant/PostStatus.java
  src/main/java/com/filmdoms/community/review/data/dto/response/MovieReviewMainPageDto.java
  src/main/java/com/filmdoms/community/review/data/entity/BaseTimeEntity.java
  src/main/java/com/filmdoms/community/review/data/entity/MovieReviewComment.java
  src/main/java/com/filmdoms/community/review/data/entity/MovieReviewContent.java
  src/main/java/com/filmdoms/community/review/data/entity/MovieReviewHeader.java
  src/main/java/com/filmdoms/community/review/repository/MovieReviewCommentRepository.java
  src/main/java/com/filmdoms/community/review/repository/MovieReviewHeaderRepository.java
  src/main/java/com/filmdoms/community/review/service/MovieReviewService.java
  src/test/java/com/filmdoms/community/review/repository/MovieReviewHeaderRepositoryTest.java
Labels: enhancement

#20 메인 페이지 - 게시글 호출 구현
  src/main/java/com/filmdoms/community/account/data/entity/Account.java
  src/main/java/com/filmdoms/community/post/controller/PostController.java
  src/main/java/com/filmdoms/community/post/data/constants/PostCategory.java
  src/main/java/com/filmdoms/community/post/data/dto/PostBriefDto.java
  src/main/java/com/filmdoms/community/post/data/dto/PostDetailDto.java
  src/main/java/com/filmdoms/community/post/data/dto/response/PostMainPageResponseDto.java
  src/main/java/com/filmdoms/community/post/data/entity/Post.java
  src/main/java/com/filmdoms/community/post/repository/PostRepository.java
  src/main/java/com/filmdoms/community/post/service/PostService.java
  src/main/java/com/filmdoms/community/postComment/controller/PostCommentController.java
  src/main/java/com/filmdoms/community/postComment/data/dto/PostCommentDto.java
  src/main/java/com/filmdoms/community/postComment/data/entity/PostComment.java
  src/main/java/com/filmdoms/community/postComment/repository/PostCommentRepository.java
  src/main/java/com/filmdoms/community/postComment/service/PostCommentService.java
  src/test/java/com/filmdoms/community/account/controller/AccountControllerTest.java
  src/test/java/com/filmdoms/community/post/controller/PostControllerTest.java
  src/test/java/com/filmdoms/community/post/service/PostServiceTest.java
Labels: enhancement

#24 없는 URI 요청도 상태코드 403으로 처리되는 버그 수정
  src/main/java/com/filmdoms/community/account/config/SecurityConfig.java
  src/main/java/com/filmdoms/community/account/exception/CustomErrorController.java
  src/main/java/com/filmdoms/community/account/exception/ErrorCode.java
  src/main/resources/application.yaml
Labels: bug

#27 프론트엔드에서 API를 호출해볼 수 있도록 dev 환경의 서버 띄우기
  src/main/resources/application.yaml
Labels: enhancement

#31 코어 엔티티 수정 및 리뷰 생성 API 구현
  src/main/java/com/filmdoms/community/account/data/entity/Account.java
  src/main/java/com/filmdoms/community/board/data/BoardContent.java
  src/main/java/com/filmdoms/community/board/data/BoardContentCore.java
  src/main/java/com/filmdoms/community/board/data/BoardHeadCore.java
  src/main/java/com/filmdoms/community/board/review/controller/MovieReviewController.java
  src/main/java/com/filmdoms/community/board/review/data/dto/request/MovieReviewCreateRequestDto.java
  src/main/java/com/filmdoms/community/board/review/data/dto/response/MovieReviewCreateResponseDto.java
  src/main/java/com/filmdoms/community/board/review/data/entity/MovieReviewComment.java
  src/main/java/com/filmdoms/community/board/review/data/entity/MovieReviewContent.java
  src/main/java/com/filmdoms/community/board/review/data/entity/MovieReviewHeader.java
  src/main/java/com/filmdoms/community/board/review/repository/MovieReviewHeaderRepository.java
  src/main/java/com/filmdoms/community/board/review/service/MovieReviewService.java
  src/main/java/com/filmdoms/community/imagefile/data/entitiy/ImageFile.java
  src/main/java/com/filmdoms/community/imagefile/service/ImageFileService.java
  src/test/java/com/filmdoms/community/board/review/data/entity/MovieReviewContentTest.java
  src/test/java/com/filmdoms/community/board/review/repository/MovieReviewHeaderRepositoryTest.java
Labels: enhancement

#33 기존의 게시글을 코어 엔티티를 적용해 리팩토링
  src/main/java/com/filmdoms/community/board/post/controller/PostCommentController.java
  src/main/java/com/filmdoms/community/board/post/controller/PostController.java
  src/main/java/com/filmdoms/community/board/post/data/constants/PostCategory.java
  src/main/java/com/filmdoms/community/board/post/data/dto/PostAccountDto.java
  src/main/java/com/filmdoms/community/board/post/data/dto/PostBriefDto.java
  src/main/java/com/filmdoms/community/board/post/data/dto/PostCommentDto.java
  src/main/java/com/filmdoms/community/board/post/data/dto/PostDetailDto.java
  src/main/java/com/filmdoms/community/board/post/data/dto/response/PostMainPageResponseDto.java
  src/main/java/com/filmdoms/community/board/post/data/entity/PostComment.java
  src/main/java/com/filmdoms/community/board/post/data/entity/PostHeader.java
  src/main/java/com/filmdoms/community/board/post/repository/PostCommentRepository.java
  src/main/java/com/filmdoms/community/board/post/repository/PostHeaderRepository.java
  src/main/java/com/filmdoms/community/board/post/service/PostCommentService.java
  src/main/java/com/filmdoms/community/board/post/service/PostService.java
  src/main/java/com/filmdoms/community/post/data/dto/PostBriefDto.java
  src/main/java/com/filmdoms/community/post/data/entity/Post.java
  src/main/java/com/filmdoms/community/post/repository/PostRepository.java
  src/main/java/com/filmdoms/community/postComment/data/entity/PostComment.java
  src/test/java/com/filmdoms/community/post/controller/PostControllerTest.java
  src/test/java/com/filmdoms/community/post/service/PostServiceTest.java
Labels: enhancement

#36 SQL 파일을 이용해 테스트 초기 데이터 세팅
  src/main/java/com/filmdoms/community/banner/repository/BannerRepository.java
  src/main/java/com/filmdoms/community/board/banner/controller/BannerController.java
  src/main/java/com/filmdoms/community/board/banner/data/dto/BannerDto.java
  src/main/java/com/filmdoms/community/board/banner/data/dto/response/BannerResponseDto.java
  src/main/java/com/filmdoms/community/board/banner/data/entity/BannerHeader.java
  src/main/java/com/filmdoms/community/board/banner/repository/BannerRepository.java
  src/main/java/com/filmdoms/community/board/banner/service/BannerService.java
  src/main/java/com/filmdoms/community/board/data/BoardContent.java
  src/main/java/com/filmdoms/community/board/data/BoardHeadCore.java
  src/main/java/com/filmdoms/community/board/post/data/entity/PostComment.java
  src/main/java/com/filmdoms/community/board/review/data/entity/MovieReviewComment.java
  src/main/resources/application.yaml
  src/main/resources/data.sql
  src/test/java/com/filmdoms/community/banner/controller/BannerHeaderControllerTest.java
Labels: enhancement

#37 비평 게시판 CR기능 구현
  src/main/java/com/filmdoms/community/board/critic/controller/CriticBoardController.java
  src/main/java/com/filmdoms/community/board/critic/data/dto/request/post/CriticBoardPostRequestDto.java
  src/main/java/com/filmdoms/community/board/critic/data/dto/request/post/CriticBoardUpdateRequestDto.java
  src/main/java/com/filmdoms/community/board/critic/data/dto/response/CriticBoardGetResponseDto.java
  src/main/java/com/filmdoms/community/board/critic/data/entity/CriticBoardHeader.java
  src/main/java/com/filmdoms/community/board/critic/repository/CriticBoardHeaderRepository.java
  src/main/java/com/filmdoms/community/board/critic/service/CriticBoardService.java
  src/main/java/com/filmdoms/community/board/data/BaseTimeEntity.java
  src/main/java/com/filmdoms/community/imagefile/data/entitiy/ImageFile.java
  src/main/resources/application.yaml
  src/test/java/com/filmdoms/community/board/critic/service/CriticBoardServiceTest.java
Labels: enhancement

#41 ImageFile 리팩토링
  src/main/java/com/filmdoms/community/account/exception/ErrorCode.java
  src/main/java/com/filmdoms/community/board/banner/controller/BannerController.java
  src/main/java/com/filmdoms/community/board/banner/data/dto/BannerDto.java
  src/main/java/com/filmdoms/community/board/banner/data/entity/BannerHeader.java
  src/main/java/com/filmdoms/community/board/banner/service/BannerService.java
  src/main/java/com/filmdoms/community/board/notice/data/dto/response/NoticeMainPageDto.java
  src/main/java/com/filmdoms/community/board/notice/service/NoticeService.java
  src/main/java/com/filmdoms/community/imagefile/controller/FileUploadController.java
  src/main/java/com/filmdoms/community/imagefile/data/dto/ImageFileDto.java
  src/main/java/com/filmdoms/community/imagefile/data/dto/UploadedFileDto.java
  src/main/java/com/filmdoms/community/imagefile/data/dto/response/UploadedFileResponseDto.java
  src/main/java/com/filmdoms/community/imagefile/data/entitiy/ImageFile.java
  src/main/java/com/filmdoms/community/imagefile/service/AmazonS3Upload.java
  src/main/java/com/filmdoms/community/imagefile/service/AmazonS3UploadService.java
  src/main/java/com/filmdoms/community/imagefile/service/ImageFileService.java
  src/main/resources/application.yaml
  src/main/resources/data.sql
Labels: bug, enhancement

#43 CriticService 에서 ImageFile 사용 오류 수정
  src/main/java/com/filmdoms/community/board/critic/service/CriticBoardService.java
  src/main/java/com/filmdoms/community/imagefile/data/dto/ImageFileDto.java
  src/main/java/com/filmdoms/community/imagefile/data/entitiy/ImageFile.java
  src/test/java/com/filmdoms/community/board/notice/service/NoticeServiceTest.java
  src/test/java/com/filmdoms/community/board/post/controller/PostControllerTest.java
  src/test/java/com/filmdoms/community/board/post/service/PostServiceTest.java
  src/test/java/com/filmdoms/community/board/review/service/MovieReviewServiceTest.java
Labels: bug

#46 게시글 작성 기능 구현
  build.gradle
  src/main/java/com/filmdoms/community/account/config/SecurityConfig.java
  src/main/java/com/filmdoms/community/account/data/dto/response/Response.java
  src/main/java/com/filmdoms/community/account/exception/ErrorCode.java
  src/main/java/com/filmdoms/community/account/exception/GlobalControllerAdvice.java
  src/main/java/com/filmdoms/community/account/exception/ValidationMessage.java
  src/main/java/com/filmdoms/community/board/post/controller/PostController.java
  src/main/java/com/filmdoms/community/board/post/data/dto/PostAccountDto.java
  src/main/java/com/filmdoms/community/board/post/data/dto/request/PostCreateRequestDto.java
  src/main/java/com/filmdoms/community/board/post/data/dto/response/PostCreateResponseDto.java
  src/main/java/com/filmdoms/community/board/post/service/PostService.java
  src/main/resources/application.yaml
  src/test/java/com/filmdoms/community/board/notice/service/NoticeServiceTest.java
  src/test/java/com/filmdoms/community/board/post/controller/PostControllerTest.java
  src/test/java/com/filmdoms/community/board/post/service/PostServiceTest.java
  src/test/java/com/filmdoms/community/board/review/repository/MovieReviewHeaderRepositoryTest.java
  src/test/java/com/filmdoms/community/board/review/service/MovieReviewServiceTest.java
  src/test/java/com/filmdoms/community/config/TestSecurityConfig.java
Labels: bug, enhancement

#55 이미지 저장 API 생성 및 이미지 처리 로직 구현 (+ 공지-리뷰 인증 로직 추가 / JPA Auditing 테스트 버그 수정)
  src/main/java/com/filmdoms/community/account/data/dto/request/LoginRequestDto.java
  src/main/java/com/filmdoms/community/account/exception/ErrorCode.java
  src/main/java/com/filmdoms/community/board/critic/controller/CriticBoardController.java
  src/main/java/com/filmdoms/community/board/notice/controller/NoticeController.java
  src/main/java/com/filmdoms/community/board/notice/data/dto/request/NoticeCreateRequestDto.java
  src/main/java/com/filmdoms/community/board/notice/data/dto/response/NoticeCreateResponseDto.java
  src/main/java/com/filmdoms/community/board/notice/service/NoticeService.java
  src/main/java/com/filmdoms/community/board/review/controller/MovieReviewController.java
  src/main/java/com/filmdoms/community/board/review/data/dto/request/MovieReviewCreateRequestDto.java
  src/main/java/com/filmdoms/community/board/review/data/dto/request/post/MovieReviewPostDto.java
  src/main/java/com/filmdoms/community/board/review/data/dto/response/MovieReviewCreateResponseDto.java
  src/main/java/com/filmdoms/community/board/review/service/MovieReviewService.java
  src/main/java/com/filmdoms/community/imagefile/controller/FileUploadController.java
  src/main/java/com/filmdoms/community/imagefile/data/dto/response/ImageUploadResponseDto.java
  src/main/java/com/filmdoms/community/imagefile/data/entitiy/ImageFile.java
  src/main/java/com/filmdoms/community/imagefile/service/AmazonS3UploadService.java
  src/main/java/com/filmdoms/community/imagefile/service/ImageFileService.java
  src/test/java/com/filmdoms/community/annotation/DataJpaTestWithJpaAuditing.java
  src/test/java/com/filmdoms/community/board/notice/service/NoticeServiceTest.java
  src/test/java/com/filmdoms/community/board/review/repository/MovieReviewHeaderRepositoryTest.java
  src/test/java/com/filmdoms/community/board/review/service/MovieReviewServiceTest.java
  src/test/java/com/filmdoms/community/imagefile/service/AmazonS3UploadServiceTest.java
Labels: bug, enhancement

#56 게시글 업데이트 기능 구현
  src/main/java/com/filmdoms/community/account/config/SecurityConfig.java
  src/main/java/com/filmdoms/community/account/data/dto/AccountDto.java
  src/main/java/com/filmdoms/community/account/data/entity/Account.java
  src/main/java/com/filmdoms/community/account/exception/ErrorCode.java
  src/main/java/com/filmdoms/community/account/service/AccountService.java
  src/main/java/com/filmdoms/community/board/data/BoardContent.java
  src/main/java/com/filmdoms/community/board/data/BoardHeadCore.java
  src/main/java/com/filmdoms/community/board/notice/service/NoticeService.java
  src/main/java/com/filmdoms/community/board/post/controller/PostController.java
  src/main/java/com/filmdoms/community/board/post/data/dto/request/PostUpdateRequestDto.java
  src/main/java/com/filmdoms/community/board/post/data/dto/response/PostUpdateResponseDto.java
  src/main/java/com/filmdoms/community/board/post/data/entity/PostHeader.java
  src/main/java/com/filmdoms/community/board/post/repository/PostHeaderRepository.java
  src/main/java/com/filmdoms/community/board/post/service/PostCommentService.java
  src/main/java/com/filmdoms/community/board/post/service/PostService.java
  src/main/java/com/filmdoms/community/board/review/service/MovieReviewService.java
  src/main/java/com/filmdoms/community/imagefile/data/entitiy/ImageFile.java
  src/test/java/com/filmdoms/community/account/service/AccountServiceTest.java
  src/test/java/com/filmdoms/community/board/notice/service/NoticeServiceTest.java
  src/test/java/com/filmdoms/community/board/post/controller/PostControllerTest.java
  src/test/java/com/filmdoms/community/board/post/service/PostServiceTest.java
  src/test/java/com/filmdoms/community/board/review/repository/MovieReviewHeaderRepositoryTest.java
  src/test/java/com/filmdoms/community/board/review/service/MovieReviewServiceTest.java
  src/test/java/com/filmdoms/community/config/TestSecurityConfig.java
Labels: enhancement

#61 일부 서비스 테스트코드 머지 오류 수정
  src/main/java/com/filmdoms/community/account/controller/AccountController.java
  src/main/java/com/filmdoms/community/imagefile/data/entitiy/ImageFile.java
  src/test/java/com/filmdoms/community/board/notice/service/NoticeServiceTest.java
  src/test/java/com/filmdoms/community/board/review/service/MovieReviewServiceTest.java
Labels: bug

#62 ImageFile 매핑 수정
  src/main/java/com/filmdoms/community/board/banner/data/entity/BannerHeader.java
  src/main/java/com/filmdoms/community/board/banner/service/BannerService.java
  src/main/java/com/filmdoms/community/board/critic/service/CriticBoardService.java
  src/main/java/com/filmdoms/community/board/data/BoardContent.java
  src/main/java/com/filmdoms/community/board/notice/data/dto/request/NoticeCreateRequestDto.java
  src/main/java/com/filmdoms/community/board/notice/data/dto/response/NoticeMainPageDto.java
  src/main/java/com/filmdoms/community/board/notice/data/entity/NoticeHeader.java
  src/main/java/com/filmdoms/community/board/notice/service/NoticeService.java
  src/main/java/com/filmdoms/community/board/post/controller/PostController.java
  src/main/java/com/filmdoms/community/board/post/data/dto/request/PostCreateRequestDto.java
  src/main/java/com/filmdoms/community/board/post/data/dto/request/PostUpdateRequestDto.java
  src/main/java/com/filmdoms/community/board/post/data/entity/PostHeader.java
  src/main/java/com/filmdoms/community/board/post/repository/PostHeaderRepository.java
  src/main/java/com/filmdoms/community/board/post/service/PostService.java
  src/main/java/com/filmdoms/community/board/review/data/dto/request/MovieReviewCreateRequestDto.java
  src/main/java/com/filmdoms/community/board/review/data/entity/MovieReviewHeader.java
  src/main/java/com/filmdoms/community/board/review/service/MovieReviewService.java
  src/main/java/com/filmdoms/community/imagefile/data/dto/ImageFileDto.java
  src/main/java/com/filmdoms/community/imagefile/data/dto/UploadedFileDto.java
  src/main/java/com/filmdoms/community/imagefile/data/entitiy/ImageFile.java
  src/main/java/com/filmdoms/community/imagefile/service/ImageFileService.java
  src/main/resources/data.sql
  src/test/java/com/filmdoms/community/board/notice/service/NoticeServiceTest.java
  src/test/java/com/filmdoms/community/board/post/controller/PostControllerTest.java
  src/test/java/com/filmdoms/community/board/post/service/PostServiceTest.java
  src/test/java/com/filmdoms/community/board/review/service/MovieReviewServiceTest.java
Labels: enhancement
