Repository YOUNGHO0/Filmdoms_Project, pull requests merged in 2023-04, with the labels that each got.

#87 Composition 을 활용한 Create 서비스 프로토타입 구현
  src/main/java/com/filmdoms/community/account/config/SecurityConfig.java
  src/main/java/com/filmdoms/community/account/exception/ErrorCode.java
  src/main/java/com/filmdoms/community/article/config/ArticleConfig.java
  src/main/java/com/filmdoms/community/article/controller/ArticleController.java
  src/main/java/com/filmdoms/community/article/controller/converter/StringToEnumConverterCategory.java
  src/main/java/com/filmdoms/community/article/controller/converter/StringToEnumConverterTag.java
  src/main/java/com/filmdoms/community/article/data/dto/ArticleControllerToServiceDto.java
  src/main/java/com/filmdoms/community/article/data/dto/ArticleRequestDto.java
  src/main/java/com/filmdoms/community/article/data/dto/ArticleResponseDto.java
  src/main/java/com/filmdoms/community/article/data/dto/ParentRequestDto.java
  src/main/java/com/filmdoms/community/article/data/dto/notice/NoticeControllerToServiceDto.java
  src/main/java/com/filmdoms/community/article/data/dto/notice/NoticeRequestDto.java
  src/main/java/com/filmdoms/community/article/data/entity/Article.java
  src/main/java/com/filmdoms/community/article/data/entity/extra/Notice.java
  src/main/java/com/filmdoms/community/article/repository/NoticeRepository.java
  src/main/java/com/filmdoms/community/article/service/ArticleService.java
  src/main/java/com/filmdoms/community/board/critic/controller/CriticBoardController.java
  src/main/java/com/filmdoms/community/board/critic/data/dto/request/post/CriticBoardPostRequestDto.java
  src/main/java/com/filmdoms/community/board/critic/data/dto/request/post/CriticBoardUpdateRequestDto.java
  src/main/java/com/filmdoms/community/board/critic/data/dto/response/CriticBoardGetResponseDto.java
  src/main/java/com/filmdoms/community/board/critic/data/dto/response/CriticBoardSinglePageResponseDto.java
  src/main/java/com/filmdoms/community/board/critic/data/entity/CriticBoardHeader.java
  src/main/java/com/filmdoms/community/board/critic/repository/CriticBoardHeaderRepository.java
  src/main/java/com/filmdoms/community/board/critic/service/CriticBoardService.java
  src/main/java/com/filmdoms/community/imagefile/data/entitiy/ImageFile.java
Labels: enhancement

#93 추천 기능 API 개발
  src/main/java/com/filmdoms/community/account/exception/ErrorCode.java
  src/main/java/com/filmdoms/community/article/data/entity/Article.java
  src/main/java/com/filmdoms/community/vote/controller/VoteController.java
  src/main/java/com/filmdoms/community/vote/data/dto/VoteResponseDto.java
  src/main/java/com/filmdoms/community/vote/data/entity/Vote.java
  src/main/java/com/filmdoms/community/vote/data/entity/VoteKey.java
  src/main/java/com/filmdoms/community/vote/repository/VoteRepository.java
  src/main/java/com/filmdoms/community/vote/service/VoteService.java
  src/test/java/com/filmdoms/community/vote/controller/VoteControllerTest.java
  src/test/java/com/filmdoms/community/vote/service/VoteServiceTest.java
Labels: enhancement

#94 게시글 상세 조회 API 구현
  src/main/java/com/filmdoms/community/account/data/dto/response/DetailPageAccountResponseDto.java
  src/main/java/com/filmdoms/community/account/data/dto/response/SimpleAccountResponseDto.java
  src/main/java/com/filmdoms/community/account/data/entity/Account.java
  src/main/java/com/filmdoms/community/account/exception/ErrorCode.java
  src/main/java/com/filmdoms/community/article/controller/ArticleController2.java
  src/main/java/com/filmdoms/community/article/data/dto/response/ArticleMainPageResponseDto.java
  src/main/java/com/filmdoms/community/article/data/dto/response/CriticMainPageResponseDto.java
  src/main/java/com/filmdoms/community/article/data/dto/response/MainPageResponseDto.java
  src/main/java/com/filmdoms/community/article/data/dto/response/NoticeMainPageResponseDto.java
  src/main/java/com/filmdoms/community/article/data/dto/response/detail/ArticleDetailResponseDto.java
  src/main/java/com/filmdoms/community/article/data/dto/response/detail/NoticeDetailResponseDto.java
  src/main/java/com/filmdoms/community/article/data/dto/response/mainpage/CriticMainPageResponseDto.java
  src/main/java/com/filmdoms/community/article/data/dto/response/mainpage/MovieAndRecentMainPageResponseDto.java
  src/main/java/com/filmdoms/community/article/data/dto/response/mainpage/NoticeMainPageResponseDto.java
  src/main/java/com/filmdoms/community/article/data/dto/response/mainpage/ParentMainPageResponseDto.java
  src/main/java/com/filmdoms/community/article/repository/ArticleRepository.java
  src/main/java/com/filmdoms/community/article/repository/NoticeRepository.java
  src/main/java/com/filmdoms/community/article/service/ArticleService.java
  src/main/java/com/filmdoms/community/article/service/InitService.java
  src/main/java/com/filmdoms/community/file/data/entity/File.java
  src/main/java/com/filmdoms/community/file/repository/FileRepository.java
  src/main/java/com/filmdoms/community/newcomment/data/dto/response/NewCommentResponseDto.java
  src/main/java/com/filmdoms/community/newcomment/data/dto/response/ParentNewCommentResponseDto.java
  src/main/java/com/filmdoms/community/newcomment/repository/NewCommentRepository.java
Labels: documentation

#98 게시글 상세 API 응답에 로그인 사용자 추천 여부 추가
  src/main/java/com/filmdoms/community/article/controller/ArticleController2.java
  src/main/java/com/filmdoms/community/article/data/dto/response/FilmUniverseMainPageResponseDto.java
  src/main/java/com/filmdoms/community/article/data/dto/response/detail/ArticleDetailResponseDto.java
  src/main/java/com/filmdoms/community/article/data/dto/response/detail/FilmUniverseDetailResponseDto.java
  src/main/java/com/filmdoms/community/article/service/ArticleService.java
Labels: enhancement

#100 배너 리팩토링
  src/main/java/com/filmdoms/community/banner/controller/BannerController.java
  src/main/java/com/filmdoms/community/banner/data/dto/request/BannerRequestDto.java
  src/main/java/com/filmdoms/community/banner/data/dto/response/BannerResponseDto.java
  src/main/java/com/filmdoms/community/banner/data/entity/Banner.java
  src/main/java/com/filmdoms/community/banner/repository/BannerRepository.java
  src/main/java/com/filmdoms/community/banner/service/BannerService.java
  src/main/java/com/filmdoms/community/board/banner/controller/BannerController.java
  src/main/java/com/filmdoms/community/board/banner/data/dto/BannerDto.java
  src/main/java/com/filmdoms/community/board/banner/data/dto/response/BannerInfoResponseDto.java
  src/main/java/com/filmdoms/community/board/banner/data/dto/response/BannerMainPageGetResponseDto.java
  src/main/java/com/filmdoms/community/board/banner/data/entity/BannerHeader.java
  src/main/java/com/filmdoms/community/board/banner/repository/BannerHeaderRepository.java
  src/main/java/com/filmdoms/community/board/banner/service/BannerService.java
  src/main/resources/data.sql
  src/test/java/com/filmdoms/community/banner/controller/BannerControllerTest.java
  src/test/java/com/filmdoms/community/banner/service/BannerServiceTest.java
  src/test/java/com/filmdoms/community/board/banner/service/BannerHeaderServiceTest.java
Labels: enhancement

#104 댓글 조회 API 분리
  src/main/java/com/filmdoms/community/article/controller/ArticleController2.java
  src/main/java/com/filmdoms/community/article/data/dto/response/detail/ArticleDetailResponseDto.java
  src/main/java/com/filmdoms/community/article/data/dto/response/detail/FilmUniverseDetailResponseDto.java
  src/main/java/com/filmdoms/community/article/service/ArticleService.java
  src/main/java/com/filmdoms/community/newcomment/controller/NewCommentController.java
  src/main/java/com/filmdoms/community/newcomment/data/dto/response/DetailPageCommentResponseDto.java
  src/main/java/com/filmdoms/community/newcomment/service/NewCommentService.java
Labels: enhancement

#108 메인페이지 응답 형태 수정
  src/main/java/com/filmdoms/community/article/controller/ArticleController2.java
  src/main/java/com/filmdoms/community/article/data/dto/response/boardlist/CriticListDto.java
  src/main/java/com/filmdoms/community/article/data/dto/response/boardlist/CriticListResponseResponseDto.java
  src/main/java/com/filmdoms/community/article/data/dto/response/boardlist/FilmUniverseListDto.java
  src/main/java/com/filmdoms/community/article/data/dto/response/boardlist/FilmUniverseListResponseResponseDto.java
  src/main/java/com/filmdoms/community/article/data/dto/response/boardlist/MovieListDto.java
  src/main/java/com/filmdoms/community/article/data/dto/response/boardlist/MovieListResponseResponseDto.java
  src/main/java/com/filmdoms/community/article/data/dto/response/boardlist/ParentBoardListResponseDto.java
  src/main/java/com/filmdoms/community/article/data/dto/response/detail/ArticleDetailResponseDto.java
  src/main/java/com/filmdoms/community/article/data/dto/response/mainpage/CriticMainPageResponseDto.java
  src/main/java/com/filmdoms/community/article/service/ArticleService.java
  src/main/java/com/filmdoms/community/board/comment/data/dto/CommentResponseDto.java
  src/main/java/com/filmdoms/community/board/notice/data/dto/response/NoticeDetailResponseDto.java
  src/main/java/com/filmdoms/community/newcomment/data/dto/response/NewCommentResponseDto.java
Labels: enhancement

#111 댓글 CUD 기능 구현
  src/main/java/com/filmdoms/community/account/exception/ErrorCode.java
  src/main/java/com/filmdoms/community/account/service/AccountService.java
  src/main/java/com/filmdoms/community/newcomment/controller/NewCommentController.java
  src/main/java/com/filmdoms/community/newcomment/data/dto/request/NewCommentCreateRequestDto.java
  src/main/java/com/filmdoms/community/newcomment/data/dto/request/NewCommentUpdateRequestDto.java
  src/main/java/com/filmdoms/community/newcomment/data/dto/response/NewCommentCreateResponseDto.java
  src/main/java/com/filmdoms/community/newcomment/data/entity/NewComment.java
  src/main/java/com/filmdoms/community/newcomment/repository/NewCommentRepository.java
  src/main/java/com/filmdoms/community/newcomment/service/NewCommentService.java
  src/test/java/com/filmdoms/community/newcomment/service/NewCommentServiceTest.java
Labels: enhancement

#117 회원 관련 기능 구현
  src/main/java/com/filmdoms/community/account/controller/AccountController.java
  src/main/java/com/filmdoms/community/account/data/dto/request/DeleteAccountRequestDto.java
  src/main/java/com/filmdoms/community/account/data/dto/request/JoinRequestDto.java
  src/main/java/com/filmdoms/community/account/data/dto/request/UpdatePasswordRequestDto.java
  src/main/java/com/filmdoms/community/account/data/dto/request/UpdateProfileRequestDto.java
  src/main/java/com/filmdoms/community/account/data/dto/response/AccountResponseDto.java
  src/main/java/com/filmdoms/community/account/data/entity/Account.java
  src/main/java/com/filmdoms/community/account/exception/ErrorCode.java
  src/main/java/com/filmdoms/community/account/exception/ValidationMessage.java
  src/main/java/com/filmdoms/community/account/repository/AccountRepository.java
  src/main/java/com/filmdoms/community/account/service/AccountService.java
  src/test/java/com/filmdoms/community/account/service/AccountServiceTest.java
Labels: enhancement

#120 댓글 추천 기능 구현
  src/main/java/com/filmdoms/community/newcomment/controller/NewCommentController.java
  src/main/java/com/filmdoms/community/newcomment/data/dto/response/NewCommentVoteResponseDto.java
  src/main/java/com/filmdoms/community/newcomment/data/entity/NewComment.java
  src/main/java/com/filmdoms/community/newcomment/data/entity/NewCommentVote.java
  src/main/java/com/filmdoms/community/newcomment/data/entity/NewCommentVoteKey.java
  src/main/java/com/filmdoms/community/newcomment/repository/NewCommentVoteRepository.java
  src/main/java/com/filmdoms/community/newcomment/service/NewCommentService.java
  src/test/java/com/filmdoms/community/newcomment/service/NewCommentServiceTest.java
Labels: enhancement

#123 이메일 인증/임시 비밀번호 발급 API 구현
  build.gradle
  src/main/java/com/filmdoms/community/account/config/AsyncConfig.java
  src/main/java/com/filmdoms/community/account/config/RedisConfig.java
  src/main/java/com/filmdoms/community/account/controller/EmailController.java
  src/main/java/com/filmdoms/community/account/data/dto/request/AuthCodeVerificationRequestDto.java
  src/main/java/com/filmdoms/community/account/data/dto/request/SimpleEmailRequestDto.java
  src/main/java/com/filmdoms/community/account/exception/ErrorCode.java
  src/main/java/com/filmdoms/community/account/service/AsyncEmailSendService.java
  src/main/java/com/filmdoms/community/account/service/EmailService.java
  src/main/java/com/filmdoms/community/account/service/utils/PasswordUtil.java
  src/main/java/com/filmdoms/community/account/service/utils/RedisUtil.java
  src/main/resources/application.yaml
  src/test/java/com/filmdoms/community/account/service/EmailServiceTest.java
Labels: enhancement

#130 엔티티 생성 로직 보강
  src/main/java/com/filmdoms/community/article/data/entity/extra/Critic.java
  src/main/java/com/filmdoms/community/article/data/entity/extra/FilmUniverse.java
  src/test/java/com/filmdoms/community/article/data/entity/extra/CriticTest.java
  src/test/java/com/filmdoms/community/article/data/entity/extra/FilmUniverseTest.java
  src/test/java/com/filmdoms/community/comment/service/CommentServiceTest.java
  src/test/java/com/filmdoms/community/testentityprovider/TestAccountProvider.java
Labels: enhancement

#134 댓글 응답에 추천 수 필드 추가
  src/main/java/com/filmdoms/community/article/data/entity/Article.java
  src/main/java/com/filmdoms/community/article/service/InitService.java
  src/main/java/com/filmdoms/community/comment/data/dto/response/CommentResponseDto.java
  src/main/java/com/filmdoms/community/comment/data/entity/Comment.java
Labels: bug

#141 파일 업로드, 게시글 생성 API 변경
  src/main/java/com/filmdoms/community/account/exception/ErrorCode.java
  src/main/java/com/filmdoms/community/account/service/AccountService.java
  src/main/java/com/filmdoms/community/article/controller/ArticleController.java
  src/main/java/com/filmdoms/community/article/controller/ArticleController2.java
  src/main/java/com/filmdoms/community/article/controller/ArticleInfoController.java
  src/main/java/com/filmdoms/community/article/data/constant/Tag.java
  src/main/java/com/filmdoms/community/article/data/dto/ArticleControllerToServiceDto.java
  src/main/java/com/filmdoms/community/article/data/dto/ArticleRequestDto.java
  src/main/java/com/filmdoms/community/article/data/dto/ParentRequestDto.java
  src/main/java/com/filmdoms/community/article/data/dto/filmuniverse/FilmUniverseControllerToServiceDto.java
  src/main/java/com/filmdoms/community/article/data/dto/filmuniverse/FilmUniverseRequestDto.java
  src/main/java/com/filmdoms/community/article/data/dto/request/create/ArticleCreateRequestDto.java
  src/main/java/com/filmdoms/community/article/data/dto/request/create/CriticCreateRequestDto.java
  src/main/java/com/filmdoms/community/article/data/dto/request/create/FilmUniverseCreateRequestDto.java
  src/main/java/com/filmdoms/community/article/data/dto/request/create/ParentCreateRequestDto.java
  src/main/java/com/filmdoms/community/article/data/dto/response/create/ArticleCreateResponseDto.java
  src/main/java/com/filmdoms/community/article/data/dto/response/enuminfo/CategoryListDto.java
  src/main/java/com/filmdoms/community/article/data/dto/response/enuminfo/TagListDto.java
  src/main/java/com/filmdoms/community/article/data/entity/Article.java
  src/main/java/com/filmdoms/community/article/data/entity/extra/FilmUniverse.java
  src/main/java/com/filmdoms/community/article/repository/CriticRepository.java
  src/main/java/com/filmdoms/community/article/repository/FilmUniverseRepository.java
  src/main/java/com/filmdoms/community/article/service/ArticleService.java
  src/main/java/com/filmdoms/community/banner/service/BannerService.java
  src/main/java/com/filmdoms/community/board/post/service/PostService.java
  src/main/java/com/filmdoms/community/file/controller/FileController.java
  src/main/java/com/filmdoms/community/file/data/dto/response/FileDetailResponseDto.java
  src/main/java/com/filmdoms/community/file/data/dto/response/FileUploadResponseDto.java
  src/main/java/com/filmdoms/community/file/data/dto/response/ImageUploadResponseDto.java
  src/main/java/com/filmdoms/community/file/service/AmazonS3UploadService.java
  src/main/java/com/filmdoms/community/file/service/ImageFileService.java
  src/test/java/com/filmdoms/community/account/service/AccountServiceTest.java
  src/test/java/com/filmdoms/community/article/service/ArticleServiceTest.java
  src/test/java/com/filmdoms/community/banner/service/BannerServiceTest.java
  src/test/java/com/filmdoms/community/board/post/service/PostServiceTest.java
  src/test/java/com/filmdoms/community/file/service/AmazonS3UploadServiceTest.java
  src/test/java/com/filmdoms/community/testentityprovider/TestAccountProvider.java
  src/test/java/com/filmdoms/community/testentityprovider/TestFileProvider.java
Labels: enhancement

#143 yml 파일 설정 오류 해결
  src/main/java/com/filmdoms/community/CommunityApplication.java
  src/main/java/com/filmdoms/community/account/config/AmazonS3Config.java
  src/main/java/com/filmdoms/community/account/config/RedisConfig.java
  src/main/java/com/filmdoms/community/account/config/SecurityConfig.java
  src/main/java/com/filmdoms/community/account/config/YamlPropertySourceFactory.java
  src/main/resources/config/mail/application.yml
  src/main/resources/config/oauth/application.yml
  src/main/resources/config/redis/application.yml
  src/main/resources/config/s3/application.yml
Labels: bug

#145 관심 영화 구현
  src/main/java/com/filmdoms/community/account/data/dto/request/JoinRequestDto.java
  src/main/java/com/filmdoms/community/account/data/dto/request/UpdateProfileRequestDto.java
  src/main/java/com/filmdoms/community/account/data/dto/response/AccountResponseDto.java
  src/main/java/com/filmdoms/community/account/data/entity/FavoriteMovie.java
  src/main/java/com/filmdoms/community/account/data/entity/Movie.java
  src/main/java/com/filmdoms/community/account/exception/ValidationMessage.java
  src/main/java/com/filmdoms/community/account/repository/FavoriteMovieRepository.java
  src/main/java/com/filmdoms/community/account/repository/MovieRepository.java
  src/main/java/com/filmdoms/community/account/service/AccountService.java
  src/test/java/com/filmdoms/community/account/service/AccountServiceTest.java
Labels: enhancement
